#
# Pass variables with --build-arg option
# UBUNTU_VER  : 16.04 or 18.04
# MY_REGISTRY : Your Container Registry
# 
ARG UBUNTU_VER=18.04
ARG MY_REGISTRY=daisukeiot

#
# Use Base image built in the previous step
#
FROM ${MY_REGISTRY}/openvino-container:baseos-ubuntu_${UBUNTU_VER}

#
# Local variables
#
ARG OPENVINO_VER=2020.2.120
ARG OPENVINO=l_openvino_toolkit_p_${OPENVINO_VER}
ARG OPENVINO_INSTALL=/opt/intel/openvino_${OPENVINO_VER}
ARG INSTALL_DIR=/opt/intel/openvino
ARG OPENVINO_DOWNLOAD=http://registrationcenter-download.intel.com/akdlm/irc_nas/16612/l_openvino_toolkit_p_2020.2.120.tgz

#
# Run as root to install OpenVINO Toolkit
#
USER root

#
# Use /tmp folder
#
WORKDIR /tmp

#
# Download OpenVINO Toolkit
# Run silent install
# Setup environment variable
RUN curl -LOJ "${OPENVINO_DOWNLOAD}" && \
    tar -xzf ./*.tgz && \
    cd l_openvino_toolkit* && \
    ./install.sh --list_components && \
    sed -i 's/decline/accept/g' silent.cfg && \
    ./install.sh -s silent.cfg && \
    rm -rf /tmp/* && \
    cd $INSTALL_DIR/install_dependencies && \
    $INSTALL_DIR/install_dependencies/install_openvino_dependencies.sh && \
    echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/openvino/.bashrc

ENV INSTALLDIR ${INSTALL_DIR}

#
# Set user to openvino and current directory to /home/openvino
#
USER openvino
WORKDIR /home/openvino

ENTRYPOINT []