#
# Ubuntu 18.04
#
FROM ubuntu:18.04

#
# Run as root user
#
USER root
WORKDIR /

#
# Install libraries
#
RUN apt-get update && \
    apt install -y --no-install-recommends \
                autoconf \
                automake \
                build-essential \
                cmake \
                cpio \
                curl \
                gnupg2 \
                libdrm2 \
                libglib2.0-0 \
                lsb-release \
                libgtk-3-0 \
                libtool \
                python3-pip \
                udev \
                unzip \
                ocl-icd-libopencl1 \
                python3-setuptools && \
    rm -rf /var/lib/apt/lists/*

#
# Create user `openvino`
#
RUN useradd -ms /bin/bash -G video,users openvino && \
   chown openvino -R /home/openvino

USER openvino
WORKDIR /home/openvino

ENTRYPOINT []
