ARG UBUNTU_VER=18.04
ARG MY_REGISTRY=daisukeiot
ARG OPENVINO_VER=2019.3.376

FROM ${MY_REGISTRY}/openvino-toolkit:${UBUNTU_VER}_${OPENVINO_VER}

#
# Run as root
#
USER root

#
# Install sudo
#
RUN apt-get update && \
    apt install -y --no-install-recommends sudo && \
    rm -rf /var/lib/apt/lists/*

# RUN adduser --home /home/openvino --disabled-password --gecos '' openvino && \
#    usermod -aG sudo openvino && \
#    echo "%sudo  ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd && \
#    usermod -aG video openvino

COPY ./dockerfile/verify.sh /home/openvino/verify.sh
RUN chmod a+x /home/openvino/verify.sh && \
    usermod -aG sudo openvino && \
    echo "%sudo  ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd

USER openvino
WORKDIR /home/openvino

RUN /opt/intel/openvino/bin/setupvars.sh && \
   cd /opt/intel/openvino/deployment_tools/demo && \
   ./demo_squeezenet_download_convert_run.sh

# ENTRYPOINT ["/home/openvino/verify.sh"]
ENTRYPOINT []
